# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nb.proto',
  package='nbclassifier',
  syntax='proto2',
  serialized_pb=_b('\n\x08nb.proto\x12\x0cnbclassifier\"\'\n\x05Train\x12\x0e\n\x06xtrain\x18\x01 \x02(\t\x12\x0e\n\x06ytrain\x18\x02 \x02(\t\"\x18\n\x07Predict\x12\r\n\x05ytest\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAIN = _descriptor.Descriptor(
  name='Train',
  full_name='nbclassifier.Train',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xtrain', full_name='nbclassifier.Train.xtrain', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ytrain', full_name='nbclassifier.Train.ytrain', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)


_PREDICT = _descriptor.Descriptor(
  name='Predict',
  full_name='nbclassifier.Predict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ytest', full_name='nbclassifier.Predict.ytest', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Train'] = _TRAIN
DESCRIPTOR.message_types_by_name['Predict'] = _PREDICT

Train = _reflection.GeneratedProtocolMessageType('Train', (_message.Message,), dict(
  DESCRIPTOR = _TRAIN,
  __module__ = 'nb_pb2'
  # @@protoc_insertion_point(class_scope:nbclassifier.Train)
  ))
_sym_db.RegisterMessage(Train)

Predict = _reflection.GeneratedProtocolMessageType('Predict', (_message.Message,), dict(
  DESCRIPTOR = _PREDICT,
  __module__ = 'nb_pb2'
  # @@protoc_insertion_point(class_scope:nbclassifier.Predict)
  ))
_sym_db.RegisterMessage(Predict)


# @@protoc_insertion_point(module_scope)
